# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_times',
            field=models.IntegerField(default=0),
        ),
    ]
