# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='the_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='the_courses.Description'),
            preserve_default=False,
        ),
    ]
